# Generated by Django 4.2.8 on 2024-05-25 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('contact_details', models.JSONField()),
            ],
        ),
    ]
