# Generated by Django 4.2.8 on 2024-05-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atmsite',
            table='atm_site',
        ),
    ]
