# Generated by Django 4.2.8 on 2024-05-25 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atm_management', '0002_alter_atmsite_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('atm_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='atm_management.atmsite')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('atm_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='atm_management.atmsite')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
