# Generated by Django 5.0.6 on 2024-05-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_management', '0003_state_city'),
    ]

    operations = [
    ]
